services:
  # Cloudflare WARP 代理服务
  warp:
    image: caomingjun/warp
    container_name: deepinfra-warp
    restart: unless-stopped
    device_cgroup_rules:
      - 'c 10:200 rwm'
    environment:
      - WARP_SLEEP=2
      - WARP_LICENSE_KEY=${WARP_LICENSE_KEY:-}
    cap_add:
      - MKNOD
      - AUDIT_WRITE
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./warp-data:/var/lib/cloudflare-warp
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD", "curl", "--socks5-hostname", "127.0.0.1:1080", "https://cloudflare.com/cdn-cgi/trace"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - warp

  deepinfra-proxy:
    build: .
    container_name: ${BACKEND_HOST:-deepinfra-proxy}
    restart: unless-stopped
    environment:
      - PORT=${BACKEND_PORT:-8000}
      - VALID_API_KEYS=${VALID_API_KEYS:-linux.do}
      - MAX_RETRIES=${MAX_RETRIES:-3}
      - RETRY_DELAY=${RETRY_DELAY:-1000}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-30000}
      - DEEPINFRA_MIRRORS=${DEEPINFRA_MIRRORS:-}
      # 如果启用 WARP，配置代理
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    profiles:
      - app

  nginx:
    image: nginx:alpine
    container_name: deepinfra-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - deepinfra-proxy
    networks:
      - proxy-network
    profiles:
      - app

networks:
  proxy-network:
    driver: bridge