# Z2API Docker Compose 配置
# 使用方法：
# 1. 运行：docker compose up -d --build
# 2. 停止：docker compose down
# 3. 查看日志：docker compose logs -f

version: '3.8'

services:
  z2api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: z2api-service
    ports:
      - "8080:8080"  # 应用硬编码端口 8080
    restart: unless-stopped
    
    # 健康检查配置
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # 网络配置
    networks:
      - z2api-network
    
    # 标签
    labels:
      - "com.z2api.description=Z.AI API Proxy Service"
      - "com.z2api.version=1.0"
      - "com.z2api.maintainer=z2api-team"

networks:
  z2api-network:
    driver: bridge
    name: z2api-network
